-- =============================================================================
-- restaurantes-e2-analytics · Data Warehouse · Dimensional model (STAR schema)
-- =============================================================================
-- Grain & design notes live in docs/data-model.md. This file is idempotent and
-- is applied by Airflow / `make warehouse-init` before the first ETL run.
--
-- Conformed dimensions (shared by every fact): dim_date, dim_time, dim_user,
-- dim_product, dim_location, dim_order_status.
-- Facts: fact_order_items (line grain), fact_orders (header grain),
-- fact_reservations (reservation grain).
--
-- Surrogate keys are integers generated by Spark (monotonically) and are the
-- ONLY join keys used by the cubes / dashboards. The natural/business ids are
-- kept for lineage back to the OLTP source (Proyecto 1).
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS dw;
SET search_path TO dw, public;

-- -----------------------------------------------------------------------------
-- DIMENSIONS
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS dw.fact_order_items   CASCADE;
DROP TABLE IF EXISTS dw.fact_orders        CASCADE;
DROP TABLE IF EXISTS dw.fact_reservations  CASCADE;
DROP TABLE IF EXISTS dw.dim_date           CASCADE;
DROP TABLE IF EXISTS dw.dim_time           CASCADE;
DROP TABLE IF EXISTS dw.dim_user           CASCADE;
DROP TABLE IF EXISTS dw.dim_product        CASCADE;
DROP TABLE IF EXISTS dw.dim_location       CASCADE;
DROP TABLE IF EXISTS dw.dim_order_status   CASCADE;

CREATE TABLE dw.dim_date (
    date_key      INTEGER PRIMARY KEY,        -- yyyymmdd
    full_date     DATE        NOT NULL,
    year          SMALLINT    NOT NULL,
    quarter       SMALLINT    NOT NULL,        -- 1..4
    quarter_label TEXT        NOT NULL,        -- 'Q1'..'Q4'
    month         SMALLINT    NOT NULL,        -- 1..12
    month_name    TEXT        NOT NULL,        -- 'enero'..'diciembre'
    month_label   TEXT        NOT NULL,        -- 'YYYY-MM' for easy sorting
    day           SMALLINT    NOT NULL,
    day_of_week   SMALLINT    NOT NULL,        -- 1=Mon .. 7=Sun (ISO)
    day_name      TEXT        NOT NULL,        -- 'lunes'..'domingo'
    is_weekend    BOOLEAN     NOT NULL
);

CREATE TABLE dw.dim_time (
    time_key   SMALLINT PRIMARY KEY,           -- hour of day 0..23
    hour       SMALLINT NOT NULL,
    hour_label TEXT     NOT NULL,              -- '00:00'..'23:00'
    daypart    TEXT     NOT NULL               -- madrugada/manana/tarde/noche
);

CREATE TABLE dw.dim_user (
    user_key    INTEGER PRIMARY KEY,
    user_id     TEXT        NOT NULL UNIQUE,    -- natural id from OLTP
    full_name   TEXT        NOT NULL,
    email       TEXT,
    signup_date DATE,
    location_key INTEGER     NOT NULL           -- snowflake link to dim_location
);

CREATE TABLE dw.dim_product (
    product_key   INTEGER PRIMARY KEY,
    product_id    TEXT        NOT NULL UNIQUE,
    product_name  TEXT        NOT NULL,
    category      TEXT        NOT NULL,         -- denormalised into the dim (STAR)
    unit_price    NUMERIC(12,2) NOT NULL,
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE
);

CREATE TABLE dw.dim_location (
    location_key INTEGER PRIMARY KEY,
    province     TEXT    NOT NULL,             -- e.g. 'San Jose'
    canton       TEXT    NOT NULL,
    district     TEXT    NOT NULL,
    zone         TEXT    NOT NULL,             -- coarse GAM delivery zone
    latitude     DOUBLE PRECISION,
    longitude    DOUBLE PRECISION
);

CREATE TABLE dw.dim_order_status (
    status_key  SMALLINT PRIMARY KEY,
    status      TEXT NOT NULL UNIQUE,          -- pending/preparing/delivered/cancelled...
    is_completed BOOLEAN NOT NULL,
    is_cancelled BOOLEAN NOT NULL
);

-- -----------------------------------------------------------------------------
-- FACTS
-- -----------------------------------------------------------------------------

-- Header grain: one row per order.
CREATE TABLE dw.fact_orders (
    order_key        BIGINT PRIMARY KEY,
    order_id         TEXT   NOT NULL UNIQUE,
    date_key         INTEGER  NOT NULL REFERENCES dw.dim_date(date_key),
    time_key         SMALLINT NOT NULL REFERENCES dw.dim_time(time_key),
    user_key         INTEGER  NOT NULL REFERENCES dw.dim_user(user_key),
    location_key     INTEGER  NOT NULL REFERENCES dw.dim_location(location_key),
    status_key       SMALLINT NOT NULL REFERENCES dw.dim_order_status(status_key),
    item_count       INTEGER  NOT NULL,        -- additive
    gross_amount     NUMERIC(14,2) NOT NULL,   -- additive
    discount_amount  NUMERIC(14,2) NOT NULL,   -- additive
    net_amount       NUMERIC(14,2) NOT NULL,   -- additive
    delivery_km      DOUBLE PRECISION,         -- distance courier->customer
    is_completed     BOOLEAN NOT NULL,
    is_cancelled     BOOLEAN NOT NULL
);

-- Line grain: one row per order line (the main sales fact for product analysis).
CREATE TABLE dw.fact_order_items (
    order_item_key BIGINT PRIMARY KEY,
    order_id       TEXT    NOT NULL,
    date_key       INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
    time_key       SMALLINT NOT NULL REFERENCES dw.dim_time(time_key),
    user_key       INTEGER NOT NULL REFERENCES dw.dim_user(user_key),
    product_key    INTEGER NOT NULL REFERENCES dw.dim_product(product_key),
    location_key   INTEGER NOT NULL REFERENCES dw.dim_location(location_key),
    status_key     SMALLINT NOT NULL REFERENCES dw.dim_order_status(status_key),
    quantity       INTEGER NOT NULL,           -- additive
    unit_price     NUMERIC(12,2) NOT NULL,
    line_amount    NUMERIC(14,2) NOT NULL       -- additive (quantity*unit_price - line discount)
);

-- Reservation grain: one row per reservation.
CREATE TABLE dw.fact_reservations (
    reservation_key BIGINT PRIMARY KEY,
    reservation_id  TEXT    NOT NULL UNIQUE,
    date_key        INTEGER NOT NULL REFERENCES dw.dim_date(date_key),
    time_key        SMALLINT NOT NULL REFERENCES dw.dim_time(time_key),
    user_key        INTEGER NOT NULL REFERENCES dw.dim_user(user_key),
    location_key    INTEGER NOT NULL REFERENCES dw.dim_location(location_key),
    party_size      INTEGER NOT NULL,          -- additive
    is_honored      BOOLEAN NOT NULL,
    is_no_show      BOOLEAN NOT NULL
);
